import { Geist, Geist_Mono, Bebas_Neue } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Image from "next/image";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${bebasNeue.variable}`}>




        <div className="layoutstyles">

          <div className="sidebar">
            <Image
              src="/rm-web-logo.png"
              alt="Logo"
              width={200}
              height={67}
              className="sidebar-logo"
              priority
            />
            <Link href="/">Live tracker</Link>
            <Link href="/leaderboard">LeaderBoard</Link>
            <Link href="/stats">My stats</Link>
            <Link href="/account">Account</Link>
          </div>
          {children}
        </div>
      </body>
    </html >
  );
}
